pipeline:
    stages:
        - stage:
              variables:
                  - name: SNYK_IMAGE
                    type: String
                    value: snyk/snyk-cli:1.745.0-maven-3.5.4
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: harness-builds
                          connectorRef: org.GKE
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+CI.variables.SNYK_IMAGE>
                                    command: |-
                                        snyk config set api=$SNYK_TOKEN
                                        snyk container test || true
                                    privileged: true
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>N")>
                                name: Snyk Container
                                identifier: Snyk_Container
                  cloneCodebase: true
              name: CI
              identifier: CI
    properties:
        ci:
            codebase:
                repoName: springbootemployee-api
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Snyk
    orgIdentifier: default
    name: Snyk Container
    identifier: Snyk_Container
    description: Test container images for vulnerabilities. See snyk container --help for full instructions.
