pipeline:
    stages:
        - stage:
              variables:
                  - value: snyk/snyk-cli:1.745.0-maven-3.5.4
                    type: String
                    name: SNYK_IMAGE
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: harness-builds
                          connectorRef: org.GKE
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    privileged: true
                                    image: <+CI.variables.SNYK_IMAGE>
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>
                                    connectorRef: org.Dockerhub
                                    command: |-
                                        snyk config set api=$SNYK_TOKEN
                                        snyk iac test || true
                                name: Snyk IaC
                                identifier: Snyk_IaC
                  cloneCodebase: true
              name: CI
              identifier: CI
    properties:
        ci:
            codebase:
                repoName: springbootemployee-api
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Snyk
    orgIdentifier: default
    name: Snyk IaC
    identifier: Snyk_IaC
    description: Find  security  issues in your Infrastructure as Code files. See snyk iac --help for full instructions.
