pipeline:
    name: SpringBoot Employee API
    identifier: SpringBoot_Employee_API
    projectIdentifier: Snyk
    orgIdentifier: default
    tags:
        SpringBoot: ""
    properties:
        ci:
            codebase:
                connectorRef: org.Github
                repoName: springbootemployee-api
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Compile
                                identifier: Compile
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+CI.variables.SNYK_IMAGE>
                                    command: |-
                                        snyk auth
                                        snyk code test || true
                                    privileged: true
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN")>
              variables:
                  - name: SNYK_IMAGE
                    type: String
                    value: snyk/snyk-cli:1.745.0-maven-3.5.4
    description: Find security issues using static code analysis. See snyk  code --help for full instructions.
