pipeline:
    tags: {}
    stages:
        - stage:
              variables:
                  - name: SNYK_IMAGE
                    type: String
                    value: snyk/snyk-cli:1.745.0-maven-3.5.4
                  - name: MAVEN_IMAGE
                    type: String
                    value: maven:3.8.3-openjdk-11-slim
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-builds
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+CI.variables.MAVEN_IMAGE>
                                    command: mvn -DskipTests -Dsnyk.skip package
                                    privileged: true
                                    envVariables:
                                        SNYK_TOKEN: <+secrets.getValue("org.SNYK_TOKEN")>N")>
                                name: Compile
                                identifier: Compile
                  cloneCodebase: true
              name: CI
              identifier: CI
    properties:
        ci:
            codebase:
                repoName: springbootemployee-api
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Snyk
    orgIdentifier: default
    name: SpringBoot Employee API
    identifier: SpringBoot_Employee_API
    description: Find security issues using static code analysis. See snyk  code --help for full instructions.
